### ISSUE TITLE
Jenkins API - Login with TOKEN 

### ISSUE THREAD

**Issue by rayeesnp** [salimfadhley/jenkinsapi#385]
There are some changes in our jenkins instance, SSO integrated with jenkins, i need to update jenkins object creation code for this

I have made changes to pass token, instance of password, but API fails with below error

Do you have any idea ?

jenkinsapi.custom_exceptions.JenkinsAPIException
JenkinsAPIException: Cannot parse <!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>OpenAM</title>
</head>

<body>

    <div id="messages"></div>
    <div id="wrapper">Loading...</div>
    <div id="popup">
        <div id="popup-content" class="radious"></div>
    </div>
    <div id="footer"></div>
    <div id="dialog-background"></div>
    <div id="dialogs"></div>

    <script data-main="main" src="libs/requirejs-2.1.14-min.js"></script>

</body>
</html>

**Comment by rayeesnp** [comment]
Getting below exception in log 

ERROR:root:Inappropriate content found at https://hostnameXXXX.com/jenkins/api/python
Traceback (most recent call last):
  File "/......../Documents/..../DevEnv/VirtulEnv/flask/lib/python2.7/site-packages/jenkinsapi/jenkinsbase.py", line 83, in get_data
    return ast.literal_eval(response.text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 49, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

**Comment by lechat** [comment]
What is the full contents of Jenkins response?

**Comment by rayeesnp** [comment]
Below response i am getting from jenkins 



ERROR:root:Inappropriate content found at https://irdevtoolsapp01.company.com/jenkins/api/python
Traceback (most recent call last):
  File "/Users/namatra/Documents/Mycompany/DevEnv/VirtulEnv/flask/lib/python2.7/site-packages/jenkinsapi/jenkinsbase.py", line 83, in get_data
    return ast.literal_eval(response.text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 49, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/namatra/Documents/Mycompany/DevEnv/VirtulEnv/flask/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/namatra/Documents/Mycompany/DevEnv/VirtulEnv/flask/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/namatra/Documents/Mycompany/DevEnv/VirtulEnv/flask/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/namatra/Documents/Mycompany/DevEnv/VirtulEnv/flask/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/namatra/Documents/Mycompany/DevEnv/VirtulEnv/flask/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/namatra/Documents/Mycompany/DevEnv/VirtulEnv/flask/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/namatra/Documents/Mycompany/DevEnv/VirtulEnv/flask/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/namatra/Documents/Mycompany/DevEnv/VirtulEnv/flask/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/namatra/Documents/Mycompany/Repos/devops-regr-automation/Tools/Test/views.py", line 71, in executeTest

**Comment by lechat** [comment]
This is stack trace and not html returned from Jenkins.

Try to add ``print(response.text)`` just before line ``return ast.literal_eval(response.text)`` in "/Users/namatra/Documents/Mycompany/DevEnv/VirtulEnv/flask/lib/python2.7/site-packages/jenkinsapi/jenkinsbase.py"

**Comment by rayeesnp** [comment]
Getting below output from print(response.text)


<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>OpenAM</title>
</head>

<body>

    <div id="messages"></div>
    <div id="wrapper">Loading...</div>
    <div id="popup">
        <div id="popup-content" class="radious"></div>
    </div>
    <div id="footer"></div>
    <div id="dialog-background"></div>
    <div id="dialogs"></div>

    <script data-main="main" src="libs/requirejs-2.1.14-min.js"></script>

</body>
</html>

<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>

**Comment by lechat** [comment]
This is not response from Jenkins.

**Comment by rayeesnp** [comment]
I think its coming from SSO server, while login with token.

Any idea, how to handle this

**Comment by rayeesnp** [comment]
I have written a sample code 

__author__ = 'namatra'

import jenkinsapi, jenkins
from jenkinsapi.jenkins import Jenkins

class testJenkins:

        def __init__(self):
            pass

        def me(self):
            print "Check"

            self.serverUser = "rayees"
            self.serverPassword = "433941sdsdsdsdsdsdf23232232a0af" (TOKEN)
            self.serverName = "irdevtoolsapp01.company.com"
            self.serverPath = "/jenkins"

            self.jenkinsPyAPI = Jenkins('https://%s%s' % (self.serverName,self.serverPath), username =self.serverUser, password=self.serverPassword)
            print self.jenkinsPyAPI.get_nodes()



ob = testJenkins()
ob.me()




getting below output 
---------------------------

(flask)TUSCA09UMLVT00N:Tools namatra$ python TestEngine/JenkinsTest.py 
Check
<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>OpenAM</title>
</head>

<body>

    <div id="messages"></div>
    <div id="wrapper">Loading...</div>
    <div id="popup">
        <div id="popup-content" class="radious"></div>
    </div>
    <div id="footer"></div>
    <div id="dialog-background"></div>
    <div id="dialogs"></div>

    <script data-main="main" src="libs/requirejs-2.1.14-min.js"></script>

</body>
</html>

<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>
ERROR:root:Inappropriate content found at https://irdevtoolsapp01.company.com/jenkins/api/python
Traceback (most recent call last):
  File "/Users/namatra/Documents/Mycompany/DevEnv/VirtulEnv/flask/lib/python2.7/site-packages/jenkinsapi/jenkinsbase.py", line 86, in get_data
    return ast.literal_eval(response.text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 49, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "TestEngine/JenkinsTest.py", line 25, in <module>
    ob.me()
  File "TestEngine/JenkinsTest.py", line 19, in me
    self.jenkinsPyAPI = Jenkins('https://%s%s' % (self.serverName,self.serverPath), username =self.serverUser, password=self.serverPassword)
  File "/Users/namatra/Documents/Mycompany/DevEnv/VirtulEnv/flask/lib/python2.7/site-packages/jenkinsapi/jenkins.py", line 57, in __init__
    JenkinsBase.__init__(self, baseurl, poll=not lazy)
  File "/Users/namatra/Documents/Mycompany/DevEnv/VirtulEnv/flask/lib/python2.7/site-packages/jenkinsapi/jenkinsbase.py", line 34, in __init__
    self.poll()
  File "/Users/namatra/Documents/Mycompany/DevEnv/VirtulEnv/flask/lib/python2.7/site-packages/jenkinsapi/jenkinsbase.py", line 57, in poll
    data = self._poll(tree=tree)
  File "/Users/namatra/Documents/Mycompany/DevEnv/VirtulEnv/flask/lib/python2.7/site-packages/jenkinsapi/jenkinsbase.py", line 67, in _poll
    return self.get_data(url, tree=tree)
  File "/Users/namatra/Documents/Mycompany/DevEnv/VirtulEnv/flask/lib/python2.7/site-packages/jenkinsapi/jenkinsbase.py", line 89, in get_data
    raise JenkinsAPIException('Cannot parse %s' % response.content)
jenkinsapi.custom_exceptions.JenkinsAPIException: Cannot parse <!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>OpenAM</title>
</head>

<body>

    <div id="messages"></div>
    <div id="wrapper">Loading...</div>
    <div id="popup">
        <div id="popup-content" class="radious"></div>
    </div>
    <div id="footer"></div>
    <div id="dialog-background"></div>
    <div id="dialogs"></div>

    <script data-main="main" src="libs/requirejs-2.1.14-min.js"></script>

</body>
</html>

**Comment by lechat** [comment]
I think that the problem is not in jenkinsapi, but in your network infrastructure. There is nothing library can do, if some requests are being redirected somewhere outside jenkins w/o issuing HTTP redirect.

**Comment by rayeesnp** [comment]
Thanks let check, is there any issue with SSO
