### ISSUE TITLE
__str__ returned non-string (type Error)

### ISSUE THREAD

**Issue by Puneeth-n** [salimfadhley/jenkinsapi#432]
Ok,

I started playing with this cool library to interact with jenkins and I seem to fail at the very beginning.

I am unable to create a `server` instance with my username and API token. We use `github` for authentication and I looked up my `API token` from jenkins. 

Here is the code:
````
from jenkinsapi.jenkins import Jenkins

server = Jenkins('http://jenkins.some-org.com:80', username='Puneeth-n', password='api-token-from-jenkins')
```` 

I have pasted the traceback below for reference:
````
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/jenkinsapi/jenkins.py", line 57, in __init__
    JenkinsBase.__init__(self, baseurl, poll=not lazy)
  File "/usr/local/lib/python2.7/site-packages/jenkinsapi/jenkinsbase.py", line 35, in __init__
    self.poll()
  File "/usr/local/lib/python2.7/site-packages/jenkinsapi/jenkinsbase.py", line 59, in poll
    data = self._poll(tree=tree)
  File "/usr/local/lib/python2.7/site-packages/jenkinsapi/jenkinsbase.py", line 69, in _poll
    return self.get_data(url, tree=tree)
  File "/usr/local/lib/python2.7/site-packages/jenkinsapi/jenkinsbase.py", line 79, in get_data
    response = requester.get_url(url, params)
  File "/usr/local/lib/python2.7/site-packages/jenkinsapi/utils/requester.py", line 100, in get_url
    return requests.get(self._update_url_scheme(url), **requestKwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 594, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 196, in resolve_redirects
    **adapter_kwargs
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 344, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
TypeError: __str__ returned non-string (type Error)
````

jenkinsapi: 0.2.29
jenkins: 1.643

**Comment by lechat** [comment]
`jenkinsapi` issues http get request and the response of this request confuses `requests` library. I don't think that this is our library problem.
